import "./globals.css";
import Image from "next/image";
import { assets } from "../assets/assets";

export const metadata = {
  title: "Portfolio - NourSafta",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth dark" suppressHydrationWarning>
      <body className="antialiased leading-8 overflow-x-hidden bg-white dark:bg-[#0e0f1b] text-black dark:text-gray-100 relative">
        <div className="fixed inset-0 -z-10">
          <Image
            src={assets.background}
            alt="Background"
            layout="fill"
            objectFit="cover"
            quality={100}
            className="opacity-20"
          />
        </div>
        {children}
      </body>
    </html>
  );
}
